<?php
namespace kaikaige\dq\controllers;

use kaikaige\dq\components\DqClient;

class Controller extends \yii\web\Controller
{
    /**
     * @var DqClient
     */
    public $dq;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $this->dq = $this->module->dq;
        $this->layout = '../layouts/main';
    }
}