<?php

namespace kaikaige\dq\components;

use yii\base\Component;
use yii\db\Exception;
use yii\httpclient\Client;

class DqClient extends Component
{
    /**
     * @var string dq连接地址
     */
    public $addr;

    /**
     * @var Client
     */
    public $httpClient;

    public function init()
    {
        if (!$this->addr) {
            throw new \Exception("property addr 不能为空");
        }
        $this->httpClient = new Client(['baseUrl' => $this->addr]);
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function topicList()
    {
        $res = $this->httpClient->get('topics')->send();
        return $res->getData();
    }

    public function topicCreate($data)
    {
        return $this->httpClient
            ->post('topic')
            ->setData($data)
            ->send()
            ->getData();
    }

    public function topicView($topicName)
    {
        return $this->httpClient
            ->get('topic/' . $topicName)
            ->send()
            ->getData();
    }

    public function topicUpdate($data)
    {
        return $this->topicCreate($data);
    }

    public function topicDelete($topicName)
    {
        return $this->httpClient
            ->delete('/topic/' . $topicName)
            ->send()
            ->getData();
    }

    public function jobPush()
    {

    }

    public function jobPop()
    {

    }
}


